// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa6ah-y8rNuF4wfIbOHqKX3v-LeszG7pU',
    appId: '1:96044902648:web:433dc9efeae39463bdb30d',
    messagingSenderId: '96044902648',
    projectId: 'tp1data',
    authDomain: 'tp1data.firebaseapp.com',
    storageBucket: 'tp1data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60RfaOO3Cq0V9AYYhPO4AQcY4PyV-N_s',
    appId: '1:96044902648:android:b08723711349ab8fbdb30d',
    messagingSenderId: '96044902648',
    projectId: 'tp1data',
    storageBucket: 'tp1data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaq8waxmk-EA1bnhSlSRrAEPfQ8Xt73s',
    appId: '1:96044902648:ios:b3edf426c068c819bdb30d',
    messagingSenderId: '96044902648',
    projectId: 'tp1data',
    storageBucket: 'tp1data.appspot.com',
    iosClientId: '96044902648-ihhb0j8qe2pm4a377n454ng9sbjl5rjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWaq8waxmk-EA1bnhSlSRrAEPfQ8Xt73s',
    appId: '1:96044902648:ios:b3edf426c068c819bdb30d',
    messagingSenderId: '96044902648',
    projectId: 'tp1data',
    storageBucket: 'tp1data.appspot.com',
    iosClientId: '96044902648-ihhb0j8qe2pm4a377n454ng9sbjl5rjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMediaApp',
  );
}
